name: Python Function Trigger

on: 
  workflow_dispatch:  # This trigger allows you to manually trigger the workflow
    inputs:
      message:
        description: 'A message for the workflow'
        required: true
        default: 'Hello, World!'

jobs:
  trigger_python_function:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python3 script.py "${{ github.event.inputs.message }}"
