name: Create File Example with Debugging

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to include in the file'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: DebugShow current directory and list files before creation
        run: |
          echo "Current directory:"
          pwd
          echo "Files before creation:"
          ls -al

      - name: Create a file
        run: |
          echo "${{ github.event.inputs.message }}" > example.txt
          echo "Content of example.txt:"
          cat example.txt

      - name: Debug: Show current directory and list files after creation
        run: |
          echo "Files after creation:"
          ls -al

      - name: Commit and push the file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add example.txt
          git commit -m "Create example.txt with message"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug: Check if file is pushed
        run: |
          echo "Files after push:"
          ls -al
